import { mkdir, mkdtemp, readdir, readFile, rm, stat, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { afterEach, describe, expect, it } from 'vitest';
import { checkDocsTargets, docHref, DOC_MARKER, encodeDocName, PRIVATE_NOTICE, startsWithMarker, writeDocs } from './docs-writer.js';

const dirs: string[] = [];
async function temp() {
  const dir = await mkdtemp(join(tmpdir(), 'mocakit-docs-writer-'));
  dirs.push(dir);
  return dir;
}
afterEach(async () => {
  await Promise.all(dirs.splice(0).map((d) => rm(d, { recursive: true, force: true })));
});

const gen = (body: string) => `${DOC_MARKER} 0.4.0 -->\n${body}\n`;

describe('docs-writer helpers', () => {
  it('detects the marker with BOM and CRLF', () => {
    expect(startsWithMarker(gen('x'))).toBe(true);
    expect(startsWithMarker(`﻿${DOC_MARKER} x -->\r\nbody`)).toBe(true);
    expect(startsWithMarker('# hand written')).toBe(false);
  });

  it('encodes unsafe characters and hrefs', () => {
    expect(encodeDocName('list_widgets', /^[a-z0-9_]$/)).toEqual({ file: 'list_widgets.md', encoded: false });
    expect(encodeDocName('a b', /^[a-z0-9_]$/)).toEqual({ file: 'a%20b.md', encoded: true });
    expect(docHref('pick#1.md')).toBe('pick%231.md');
    expect(PRIVATE_NOTICE).toBe('This folder describes a licensed Blue Yonder system. Keep it in a private repository.');
  });
});

describe('writeDocs', () => {
  it('writes nested files, skips unchanged (CRLF-tolerant) and removes only stale generated files in managed dirs', async () => {
    const dir = await temp();
    await mkdir(join(dir, 'commands'), { recursive: true });
    await writeFile(join(dir, 'commands/dropped.md'), gen('old'));
    await writeFile(join(dir, 'commands/notes.md'), '# mine\n');
    await mkdir(join(dir, 'other'), { recursive: true });
    await writeFile(join(dir, 'other/stale.md'), gen('not managed'));

    const files = new Map([
      ['README.md', gen('readme')],
      ['commands/list_widgets.md', gen('a')],
    ]);
    expect(await writeDocs(dir, files, { setting: 'commandDocs.out', managedDirs: ['commands'] })).toEqual({
      written: 2,
      unchanged: 0,
      removed: ['commands/dropped.md'],
    });
    expect((await readdir(join(dir, 'commands'))).sort()).toEqual(['list_widgets.md', 'notes.md']);
    expect(await readdir(join(dir, 'other'))).toEqual(['stale.md']);

    await writeFile(join(dir, 'README.md'), gen('readme').split('\n').join('\r\n'));
    const before = (await stat(join(dir, 'README.md'))).mtimeMs;
    expect(await writeDocs(dir, files, { setting: 'commandDocs.out', managedDirs: ['commands'] })).toEqual({
      written: 0,
      unchanged: 2,
      removed: [],
    });
    expect((await stat(join(dir, 'README.md'))).mtimeMs).toBe(before);
  });

  it('tolerates a missing managed dir', async () => {
    const dir = await temp();
    await expect(writeDocs(dir, new Map([['README.md', gen('r')]]), { setting: 's', managedDirs: ['codes'] })).resolves.toEqual({
      written: 1,
      unchanged: 0,
      removed: [],
    });
  });

  it('refuses before writing anything when a target is hand-written', async () => {
    const dir = await temp();
    await mkdir(join(dir, 'commands'), { recursive: true });
    await writeFile(join(dir, 'commands/list_widgets.md'), '# my notes\n');
    const files = new Map([
      ['README.md', gen('r')],
      ['commands/list_widgets.md', gen('a')],
    ]);
    await expect(checkDocsTargets(dir, files, 'commandDocs.out')).rejects.toThrow(
      `${join(dir, 'commands', 'list_widgets.md')} exists and was not generated by mocakit; move it or choose another commandDocs.out directory`,
    );
    await expect(writeDocs(dir, files, { setting: 'commandDocs.out', managedDirs: ['commands'] })).rejects.toThrow(/was not generated by mocakit/);
    await expect(readFile(join(dir, 'README.md'), 'utf8')).rejects.toThrow();
    expect(await readFile(join(dir, 'commands/list_widgets.md'), 'utf8')).toBe('# my notes\n');
  });
});
