import { mkdir, readdir, readFile, unlink, writeFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';

/** First characters of every generated docs file; only files starting with it are ever replaced or deleted. */
export const DOC_MARKER = '<!-- Generated by mocakit';

/** Opening line of every generated README.md / INDEX.md. */
export const PRIVATE_NOTICE = 'This folder describes a licensed Blue Yonder system. Keep it in a private repository.';

export function startsWithMarker(text: string): boolean {
  const body = text.charCodeAt(0) === 0xfeff ? text.slice(1) : text;
  return (body.split(/\r?\n/, 1)[0] ?? '').startsWith(DOC_MARKER);
}

/** `name` + `.md`, with characters not matching `safe` percent-encoded as UTF-8. */
export function encodeDocName(name: string, safe: RegExp): { file: string; encoded: boolean } {
  let encoded = false;
  const file = [...name]
    .map((ch) => {
      if (safe.test(ch)) return ch;
      encoded = true;
      return [...new TextEncoder().encode(ch)].map((b) => `%${b.toString(16).toUpperCase().padStart(2, '0')}`).join('');
    })
    .join('');
  return { file: `${file}.md`, encoded };
}

/** A markdown link target for a generated file name (`%` and `#` are escaped so renderers keep them literal). */
export function docHref(file: string): string {
  return file.split('%').join('%25').split('#').join('%23');
}

const pathOf = (dir: string, relative: string): string => join(dir, ...relative.split('/'));

async function readIfExists(path: string): Promise<string | null> {
  try {
    return await readFile(path, 'utf8');
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code === 'ENOENT') return null;
    throw error;
  }
}

/** Throws if any target exists and was not generated by mocakit. `setting` names the config key to change. */
export async function checkDocsTargets(dir: string, files: ReadonlyMap<string, string>, setting: string): Promise<void> {
  for (const relative of files.keys()) {
    const path = pathOf(dir, relative);
    const current = await readIfExists(path);
    if (current !== null && !startsWithMarker(current)) {
      throw new Error(`${path} exists and was not generated by mocakit; move it or choose another ${setting} directory`);
    }
  }
}

/**
 * Writes changed files (CRLF-tolerant comparison) and deletes generated `*.md` files in `managedDirs`
 * that are no longer in `files`. Hand-written files are never touched: the pre-check throws first.
 */
export async function writeDocs(
  dir: string,
  files: ReadonlyMap<string, string>,
  options: { setting: string; managedDirs: string[] },
): Promise<{ written: number; unchanged: number; removed: string[] }> {
  await checkDocsTargets(dir, files, options.setting);
  let written = 0;
  let unchanged = 0;
  for (const [relative, content] of files) {
    const path = pathOf(dir, relative);
    const current = await readIfExists(path);
    if (current !== null && current.split('\r\n').join('\n') === content) {
      unchanged++;
      continue;
    }
    await mkdir(dirname(path), { recursive: true });
    await writeFile(path, content, 'utf8');
    written++;
  }

  const removed: string[] = [];
  for (const managed of options.managedDirs) {
    let entries;
    try {
      entries = await readdir(pathOf(dir, managed), { withFileTypes: true });
    } catch (error) {
      if ((error as NodeJS.ErrnoException).code === 'ENOENT') continue;
      throw error;
    }
    for (const entry of entries) {
      const relative = `${managed}/${entry.name}`;
      if (!entry.isFile() || !entry.name.endsWith('.md') || files.has(relative)) continue;
      const path = pathOf(dir, relative);
      if (startsWithMarker(await readFile(path, 'utf8'))) {
        await unlink(path);
        removed.push(relative);
      }
    }
  }
  return { written, unchanged, removed: removed.sort() };
}
