import { mkdir, readdir, readFile, unlink, writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import { redactUrl } from '../util/url.js';
import { describeType } from './emit-schema.js';
import type { SchemaSnapshot, SchemaTable } from './schema-snapshot.js';

/** First characters of every generated file; only files starting with it are ever deleted. */
export const DOC_MARKER = '<!-- Generated by mocakit';

const SAFE = /^[a-z0-9_$#]$/;

export function docFileName(table: string): { file: string; encoded: boolean } {
  let encoded = false;
  const name = [...table]
    .map((ch) => {
      if (SAFE.test(ch)) return ch;
      encoded = true;
      return [...new TextEncoder().encode(ch)].map((b) => `%${b.toString(16).toUpperCase().padStart(2, '0')}`).join('');
    })
    .join('');
  return { file: `${name}.md`, encoded };
}

const oneLine = (text: string): string => text.replace(/\s+/g, ' ').trim();
const cell = (text: string | undefined): string => (text === undefined ? '' : oneLine(text).replace(/\\/g, '\\\\').replace(/\|/g, '\\|'));

function readme(marker: string): string {
  return [
    marker,
    '# Database schema (for coding agents)',
    '',
    'This folder describes the tables and views of the MOCA database, generated by `mocakit generate`.',
    '',
    '- Search `INDEX.md` for candidate tables by name or description, then open `tables/<table>.md` for its columns.',
    '- Names are lowercase. Dates arrive as `YYYYMMDDHH24MISS` strings.',
    "- Query a single table with `moca.from('table').select(...).where({...}).rows()`; use `moca.exec('[select ...]')`",
    '  for joins and anything more complex. Types for every table are in `moca.schema.ts`.',
    '',
  ].join('\n');
}

function tableFile(marker: string, table: SchemaTable): string {
  const key = table.primaryKey?.length ? ` · primary key: ${table.primaryKey.join(', ')}` : '';
  const lines = [marker, `# ${table.name}`, '', `${table.kind}${key}`, ''];
  if (table.comment !== undefined) lines.push(oneLine(table.comment), '');
  lines.push('| column | type | null | key | comment |', '|---|---|---|---|---|');
  for (const column of table.columns) {
    const pk = table.primaryKey?.includes(column.name) ? 'PK' : '';
    lines.push(`| ${cell(column.name)} | ${cell(describeType(column))} | ${column.nullable ? 'yes' : 'no'} | ${pk} | ${cell(column.comment)} |`);
  }
  lines.push('');
  return lines.join('\n');
}

/** Pure: the docs folder as a map of relative path → content. */
export function emitSchemaDocs(snapshot: SchemaSnapshot, options: { version: string }): { files: Map<string, string>; warnings: string[] } {
  const marker = `${DOC_MARKER} ${options.version} from ${redactUrl(snapshot.server)}. Do not edit; regenerate with \`mocakit generate\`. -->`;
  const warnings: string[] = [];
  const files = new Map<string, string>([['README.md', readme(marker)]]);
  const index = [marker, '# Tables and views', ''];
  const tableFiles: Array<[string, string]> = [];
  for (const table of snapshot.tables) {
    const { file, encoded } = docFileName(table.name);
    if (encoded) warnings.push(`Table "${table.name}" has characters that are not safe in file names; its doc is tables/${file}`);
    const cols = `${table.columns.length} ${table.columns.length === 1 ? 'col' : 'cols'}`;
    const comment = table.comment === undefined ? '' : ` · ${oneLine(table.comment)}`;
    index.push(`- [\`${table.name}\`](tables/${file}) · ${table.kind} · ${cols}${comment}`);
    tableFiles.push([`tables/${file}`, tableFile(marker, table)]);
  }
  index.push('');
  files.set('INDEX.md', index.join('\n'));
  for (const [path, content] of tableFiles) files.set(path, content);
  return { files, warnings };
}

/** Writes changed files and deletes generated `tables/*.md` files that are no longer in `files`. */
export async function writeSchemaDocs(
  dir: string,
  files: ReadonlyMap<string, string>,
): Promise<{ written: number; unchanged: number; removed: string[] }> {
  await mkdir(join(dir, 'tables'), { recursive: true });
  let written = 0;
  let unchanged = 0;
  for (const [relative, content] of files) {
    const path = join(dir, ...relative.split('/'));
    const current = await readFile(path, 'utf8').catch(() => null);
    if (current === content) {
      unchanged++;
      continue;
    }
    await writeFile(path, content, 'utf8');
    written++;
  }

  const keep = new Set([...files.keys()].filter((k) => k.startsWith('tables/')).map((k) => k.slice('tables/'.length)));
  const removed: string[] = [];
  for (const entry of await readdir(join(dir, 'tables'), { withFileTypes: true })) {
    if (!entry.isFile() || !entry.name.endsWith('.md') || keep.has(entry.name)) continue;
    const path = join(dir, 'tables', entry.name);
    const firstLine = (await readFile(path, 'utf8')).split('\n', 1)[0] ?? '';
    if (firstLine.startsWith(DOC_MARKER)) {
      await unlink(path);
      removed.push(entry.name);
    }
  }
  return { written, unchanged, removed: removed.sort() };
}
