import { redactUrl } from '../util/url.js';
import { doc, propertyName } from './emit.js';
import { globToRegExp } from './filter.js';
import type { SchemaColumn, SchemaSnapshot, SchemaTable } from './schema-snapshot.js';

export interface SchemaFilter {
  /** Table/view name globs (`*`, `?`), case-insensitive. Default `['*']`. */
  include?: string[];
  exclude?: string[];
  /** Include views. Default `true`. */
  views?: boolean;
}

export function filterTables(tables: SchemaTable[], filter: SchemaFilter): SchemaTable[] {
  const include = (filter.include?.length ? filter.include : ['*']).map(globToRegExp);
  const exclude = (filter.exclude ?? []).map(globToRegExp);
  return tables.filter(
    (table) =>
      (filter.views !== false || table.kind !== 'view') &&
      include.some((re) => re.test(table.name)) &&
      !exclude.some((re) => re.test(table.name)),
  );
}

/** `nvarchar(20)`, `numeric(19,4)`, `numeric(10)`, `datetime`. */
export function describeType(column: SchemaColumn): string {
  if (column.length !== undefined) return `${column.type}(${column.length})`;
  if (column.precision !== undefined) {
    return column.scale !== undefined ? `${column.type}(${column.precision},${column.scale})` : `${column.type}(${column.precision})`;
  }
  return column.type;
}

export function tsColumnType(column: SchemaColumn): string {
  let type: string;
  switch (column.category) {
    case 'integer':
    case 'decimal':
      type = 'number';
      break;
    case 'boolean':
      type = 'boolean';
      break;
    case 'other':
      return 'MocaValue'; // already includes null
    default:
      type = 'string'; // string, date (YYYYMMDDHH24MISS text), binary
  }
  return column.nullable ? `${type} | null` : type;
}

function tableDoc(table: SchemaTable): string {
  const key = table.primaryKey?.length ? ` · PK ${table.primaryKey.join(', ')}` : '';
  const comment = table.comment === undefined ? '' : `${table.comment} `;
  return doc(`${comment}(${table.kind}${key})`);
}

function columnDoc(table: SchemaTable, column: SchemaColumn): string {
  const parts = [column.comment, describeType(column), table.primaryKey?.includes(column.name) ? 'PK' : undefined];
  return doc(parts.filter((part) => part !== undefined).join(' · '));
}

export function emitSchema(
  snapshot: SchemaSnapshot,
  options: { version: string; importFrom?: string },
): { code: string; warnings: string[]; count: number } {
  const { tables } = snapshot;
  const warnings = tables.length === 0 ? ['No tables matched the schema filters; moca.schema.ts has no tables'] : [];
  const usesMocaValue = tables.some((t) => t.columns.some((c) => c.category === 'other'));
  const lines = [
    `// AUTO-GENERATED by mocakit ${options.version} from ${redactUrl(snapshot.server)} — ${tables.length} tables and views.`,
    '// Do not edit by hand; regenerate with `mocakit generate`.',
    '/* eslint-disable */',
  ];
  if (usesMocaValue) lines.push(`import type { MocaValue } from '${options.importFrom ?? 'mocakit'}';`);
  lines.push('');

  if (tables.length === 0) {
    lines.push('export interface MocaTables {}', '', 'export type MocaTableName = never;', '');
    return { code: lines.join('\n'), warnings, count: 0 };
  }

  lines.push('export interface MocaTables {');
  for (const table of tables) {
    lines.push(`  /** ${tableDoc(table)} */`, `  ${propertyName(table.name)}: {`);
    for (const column of table.columns) {
      lines.push(`    /** ${columnDoc(table, column)} */`, `    ${propertyName(column.name)}: ${tsColumnType(column)};`);
    }
    lines.push('  };');
  }
  lines.push('}', '', 'export type MocaTableName = keyof MocaTables;', '');
  return { code: lines.join('\n'), warnings, count: tables.length };
}
