import { describe, expect, it } from 'vitest';
import { describeType, emitSchema, filterTables, tsColumnType } from './emit-schema.js';
import type { SchemaColumn, SchemaSnapshot, SchemaTable } from './schema-snapshot.js';

const col = (name: string, extra: Partial<SchemaColumn> = {}): SchemaColumn => ({
  name, type: 'nvarchar', category: 'string', nullable: false, ...extra,
});

const tables: SchemaTable[] = [
  {
    name: 'widget',
    kind: 'table',
    comment: 'Widgets on hand. See */ and @param.',
    primaryKey: ['widget_id'],
    columns: [
      col('widget_id', { length: 20, comment: 'Unique id.' }),
      col('qty', { type: 'numeric', category: 'decimal', nullable: true, precision: 19, scale: 4 }),
      col('moddte', { type: 'datetime', category: 'date', nullable: true }),
      col('flag', { type: 'bit', category: 'boolean' }),
      col('geo', { type: 'geography', category: 'other', nullable: true }),
      col('odd-name', { comment: 'line one\nline two' }),
    ],
  },
  { name: 'widget_view', kind: 'view', columns: [col('widget_id')] },
  { name: 'tmp_widget', kind: 'table', columns: [col('a')] },
];

const snapshot: SchemaSnapshot = {
  mocakitVersion: '0.3.0', generatedAt: 'x', server: 'https://u:p@moca.test/service', database: 'sqlserver', tables,
};

describe('describeType', () => {
  it.each([
    [col('a', { length: 20 }), 'nvarchar(20)'],
    [col('a'), 'nvarchar'],
    [col('a', { type: 'numeric', category: 'decimal', precision: 19, scale: 4 }), 'numeric(19,4)'],
    [col('a', { type: 'numeric', category: 'decimal', precision: 10 }), 'numeric(10)'],
    [col('a', { type: 'datetime', category: 'date' }), 'datetime'],
  ])('%j → %s', (column, expected) => {
    expect(describeType(column)).toBe(expected);
  });
});

describe('tsColumnType', () => {
  it.each([
    ['string', false, 'string'],
    ['date', true, 'string | null'],
    ['binary', false, 'string'],
    ['integer', false, 'number'],
    ['decimal', true, 'number | null'],
    ['boolean', false, 'boolean'],
    ['other', true, 'MocaValue'],
  ] as const)('%s nullable=%s → %s', (category, nullable, expected) => {
    expect(tsColumnType(col('a', { category, nullable }))).toBe(expected);
  });
});

describe('filterTables', () => {
  it('applies include, exclude and views', () => {
    expect(filterTables(tables, {}).map((t) => t.name)).toEqual(['widget', 'widget_view', 'tmp_widget']);
    expect(filterTables(tables, { exclude: ['TMP_*'] }).map((t) => t.name)).toEqual(['widget', 'widget_view']);
    expect(filterTables(tables, { include: ['widget*'], views: false }).map((t) => t.name)).toEqual(['widget']);
  });
});

describe('emitSchema', () => {
  const { code, warnings, count } = emitSchema(snapshot, { version: '0.3.0' });

  it('writes a redacted header and imports MocaValue only when used', () => {
    expect(code).toContain('// AUTO-GENERATED by mocakit 0.3.0 from https://moca.test/service — 3 tables and views.');
    expect(code).not.toContain('u:p@');
    expect(code).toContain("import type { MocaValue } from 'mocakit';");
    const noOther = emitSchema({ ...snapshot, tables: [tables[1]!] }, { version: '0.3.0' }).code;
    expect(noOther).not.toContain('import type');
  });

  it('emits documented table and column types', () => {
    expect(code).toContain('  /** Widgets on hand. See *\\/ and \\@param. (table · PK widget_id) */\n  widget: {');
    expect(code).toContain('    /** Unique id. · nvarchar(20) · PK */\n    widget_id: string;');
    expect(code).toContain('    /** numeric(19,4) */\n    qty: number | null;');
    expect(code).toContain('    /** datetime */\n    moddte: string | null;');
    expect(code).toContain('    flag: boolean;');
    expect(code).toContain('    geo: MocaValue;');
    expect(code).toContain('    /** line one line two · nvarchar */\n    "odd-name": string;');
    expect(code).toContain('  /** (view) */\n  widget_view: {');
    expect(code).toContain('export type MocaTableName = keyof MocaTables;');
    expect(count).toBe(3);
    expect(warnings).toEqual([]);
  });

  it('uses importFrom for the MocaValue import', () => {
    expect(emitSchema(snapshot, { version: '0.3.0', importFrom: '../../src/index.js' }).code).toContain(
      "import type { MocaValue } from '../../src/index.js';",
    );
  });

  it('emits never and warns for an empty table list', () => {
    const empty = emitSchema({ ...snapshot, tables: [] }, { version: '0.3.0' });
    expect(empty.code).toContain('export interface MocaTables {}');
    expect(empty.code).toContain('export type MocaTableName = never;');
    expect(empty.warnings).toEqual(['No tables matched the schema filters; moca.schema.ts has no tables']);
  });

  it('is deterministic', () => {
    expect(emitSchema(snapshot, { version: '0.3.0' }).code).toBe(code);
  });
});
