import { classifyMocaType } from '../protocol/moca-types.js';
import { redactUrl } from '../util/url.js';
import { assignMethodNames, isIdentifier, toPascal } from './names.js';
import type { Snapshot, SnapshotArg, SnapshotCommand } from './snapshot.js';

export interface EmitOptions {
  version: string;
  /** Module specifier for the runtime. Default `mocakit`; tests point it at `src/index.js`. */
  importFrom?: string;
}

export interface EmitResult {
  code: string;
  warnings: string[];
}

const str = (value: string): string => JSON.stringify(value);

function doc(text: string): string {
  return text.replace(/\*\//g, '*\\/').replace(/\s+/g, ' ').trim();
}

function tsType(dtype: string): string {
  switch (classifyMocaType(dtype)) {
    case 'number':
      return 'number';
    case 'boolean':
      return 'boolean';
    case 'date':
      return 'string | Date';
    default:
      return 'string';
  }
}

function propertyName(name: string): string {
  return isIdentifier(name) ? name : str(name);
}

/** Drops repeats (same name ignoring case and whitespace runs; first wins), then sorts by name. */
function normalizeCommands(commands: readonly SnapshotCommand[]): SnapshotCommand[] {
  const seen = new Set<string>();
  const unique: SnapshotCommand[] = [];
  for (const command of commands) {
    const key = command.name.trim().replace(/\s+/g, ' ').toLowerCase();
    if (seen.has(key)) continue;
    seen.add(key);
    unique.push(command);
  }
  return unique.sort((a, b) => (a.name < b.name ? -1 : a.name > b.name ? 1 : 0));
}

function emitArgsInterface(name: string, args: SnapshotArg[]): string[] {
  const lines = [`export interface ${name} {`];
  for (const arg of args) {
    const summary = doc([arg.description, arg.dtype ? `(${arg.dtype})` : ''].filter(Boolean).join(' '));
    if (summary !== '') lines.push(`  /** ${summary} */`);
    const type = tsType(arg.dtype);
    lines.push(arg.required ? `  ${propertyName(arg.name)}: ${type};` : `  ${propertyName(arg.name)}?: ${type} | null;`);
  }
  lines.push('}', '');
  return lines;
}

function emitSpec(method: string, command: SnapshotCommand): string {
  const args = command.args.map((arg) => `[${str(arg.name)}, ${str(arg.dtype)}, ${arg.required ? 1 : 0}]`).join(', ');
  return `  ${method}: [${str(command.name)}, [${args}]],`;
}

function emitMethod(method: string, argsType: string, command: SnapshotCommand): string[] {
  const hasRequired = command.args.some((arg) => arg.required);
  const generic = `<T = mk.Output<${str(command.name)}>>`;
  const summary = doc(
    [`\`${command.name}\``, command.level ? `level: ${command.level}` : '', command.description ?? ''].filter(Boolean).join(' · '),
  );
  const rowsArgs = hasRequired ? `args: ${argsType}` : `args?: ${argsType}`;
  const fullArgs = hasRequired ? `args: ${argsType}` : `args: ${argsType} | undefined`;
  return [
    `  /** ${summary} */`,
    `  ${method}${generic}(${rowsArgs}, opts?: mk.RowsOptions): Promise<T[]>;`,
    `  ${method}${generic}(${fullArgs}, opts: mk.FullOptions): Promise<mk.MocaResult<T>>;`,
    `  ${method}${generic}(${rowsArgs}, opts?: mk.CallOptions): Promise<T[] | mk.MocaResult<T>>;`,
    `  ${method}(args?: ${argsType}, opts?: mk.CallOptions): Promise<unknown> {`,
    `    return this.call(S.${method}, args, opts);`,
    '  }',
    '',
  ];
}

export function emit(snapshot: Snapshot, options: EmitOptions): EmitResult {
  const commands = normalizeCommands(snapshot.commands);
  const { names, collisions } = assignMethodNames(commands.map((command) => command.name));
  const warnings = collisions.map(
    (group) =>
      `Commands ${group.map(str).join(', ')} map to the same method name; generated ${group.map((c) => names.get(c)).join(', ')}`,
  );

  const lines: string[] = [
    `// AUTO-GENERATED by mocakit ${options.version} from ${redactUrl(snapshot.server)} — ${commands.length} commands.`,
    '// Do not edit by hand; regenerate with `mocakit generate`.',
    '/* eslint-disable */',
    `import * as mk from ${str(options.importFrom ?? 'mocakit')};`,
    '',
  ];

  lines.push(
    commands.length === 0
      ? 'export type MocaCommandName = never;'
      : `export type MocaCommandName =\n${commands.map((c) => `  | ${str(c.name)}`).join('\n')};`,
    '',
  );

  const argTypes = new Map<string, string>();
  for (const command of commands) {
    const method = names.get(command.name) as string;
    if (command.args.length === 0) {
      argTypes.set(command.name, 'mk.NoArgs');
      continue;
    }
    const interfaceName = `${toPascal(method)}Args`;
    argTypes.set(command.name, interfaceName);
    lines.push(...emitArgsInterface(interfaceName, command.args));
  }

  lines.push('const S = {');
  for (const command of commands) lines.push(emitSpec(names.get(command.name) as string, command));
  lines.push('} as const satisfies Record<string, mk.CommandSpec>;', '');

  lines.push('export class Moca extends mk.MocaClient {');
  for (const command of commands) {
    lines.push(...emitMethod(names.get(command.name) as string, argTypes.get(command.name) as string, command));
  }
  lines.push('}', '');

  lines.push(
    'export function createMoca(config: mk.MocaConfig, deps?: mk.MocaClientDeps): Moca {',
    '  return new Moca(config, deps);',
    '}',
    '',
  );

  return { code: lines.join('\n'), warnings };
}
