import { describe, expect, it } from 'vitest';
import type { ApiOperation, ApiSnapshot } from './api-snapshot.js';
import { defTypeNames, emitApi, filterOperations, tsApiType } from './emit-api.js';

const op = (over: Partial<ApiOperation> & Pick<ApiOperation, 'name' | 'method' | 'path'>): ApiOperation => ({
  group: 'Public APIs', tag: 'widget (v1)', tagKey: 'widget', fullPath: `/api${over.path}`, permissions: [], parameters: [], ...over,
});

const snapshot: ApiSnapshot = {
  mocakitVersion: '0.5.0', generatedAt: 'x', server: 'https://u:p@moca.test/service',
  groups: [{ name: 'Public APIs', basePath: '/api', private: false }],
  operations: [
    op({
      name: 'getWidgets', method: 'get', path: '/widget/v1/widgets', description: 'Lists */ widgets', permissions: ['VIEW_WIDGET'],
      parameters: [
        { in: 'query', name: 'wh_id', required: true, schema: { kind: 'string' } },
        { in: 'query', name: 'status', required: false, schema: { kind: 'string', enum: ['A', 'X'] } },
        { in: 'query', name: 'qty', required: false, schema: { kind: 'number', integer: true } },
      ],
      response: { envelope: 'data', schema: { kind: 'ref', name: 'widget.v1.Widget' } },
    }),
    op({
      name: 'postWidgetMove', method: 'post', path: '/widget/v1/widgetMove',
      body: { required: true, schema: { kind: 'object', properties: { wh_id: { kind: 'string', description: 'Warehouse' }, 'odd-name': { kind: 'boolean' } }, required: ['wh_id'] } },
      response: { envelope: 'body', schema: { kind: 'object', properties: { moved: { kind: 'number', integer: true } }, required: [] } },
    }),
    op({ name: 'deleteWidgetsByWidgetId', method: 'delete', path: '/widget/v1/widgets/{widget_id}', parameters: [{ in: 'path', name: 'widget_id', required: true, schema: { kind: 'string' } }] }),
    op({ name: 'getGizmos', method: 'get', path: '/gizmo/v1/gizmos', tag: 'gizmo (v1)', tagKey: 'gizmo' }),
  ],
  definitions: { 'widget.v1.Widget': { kind: 'object', properties: { widget_id: { kind: 'string' }, tags: { kind: 'array', items: { kind: 'string' } } }, required: ['widget_id'] } },
};

describe('helpers', () => {
  it('filters by tag key globs and methods', () => {
    expect(filterOperations(snapshot.operations, { include: ['wid*'] }).map((o) => o.name)).toEqual(['getWidgets', 'postWidgetMove', 'deleteWidgetsByWidgetId']);
    expect(filterOperations(snapshot.operations, { methods: ['get'] }).map((o) => o.name)).toEqual(['getWidgets', 'getGizmos']);
    expect(filterOperations(snapshot.operations, { exclude: ['gizmo'] })).toHaveLength(3);
  });
  it('names definition types (ruling P4)', () => {
    expect([...defTypeNames(['cws.v2.A', 'cws_v2_A', 'B'])]).toEqual([['cws.v2.A', 'Def_cws_v2_A'], ['cws_v2_A', 'Def_cws_v2_A_2'], ['B', 'Def_B']]);
  });
  it('never assigns the same type name twice', () => {
    const map = defTypeNames(['x.A', 'x_A', 'x_A_2']);
    expect([...map.values()]).toEqual(['Def_x_A', 'Def_x_A_2', 'Def_x_A_2_2']);
  });
  it('renders schema types', () => {
    const defs = new Map([['W', 'Def_W']]);
    expect(tsApiType({ kind: 'string', enum: ['A', "B'"] }, defs)).toBe('"A" | "B\'"');
    expect(tsApiType({ kind: 'array', items: { kind: 'ref', name: 'W' } }, defs)).toBe('Array<Def_W>');
    expect(tsApiType({ kind: 'ref', name: 'Missing' }, defs)).toBe('unknown');
    expect(tsApiType({ kind: 'object', properties: {}, required: [], additional: { kind: 'boolean' } }, defs)).toBe('Record<string, boolean>');
  });
});

describe('emitApi', () => {
  const { code, warnings, count } = emitApi(snapshot, { version: '0.5.0' });

  it('writes a redacted header, definitions and the spec table', () => {
    expect(code).toContain('// AUTO-GENERATED by mocakit 0.5.0 from https://moca.test/service — 4 API operations.');
    expect(code).not.toContain('u:p@');
    expect(code).toContain("import type * as mk from 'mocakit';");
    expect(code).toContain('export interface Def_widget_v1_Widget {');
    expect(code).toContain('  widget_id: string;');
    expect(code).toContain('  tags?: Array<string>;');
    expect(code).toContain('export const API = {');
    expect(code).toContain('    getWidgets: ["get", "/api/widget/v1/widgets", "data"],');
    expect(code).toContain('} as const satisfies mk.ApiSpecTable;');
    expect(count).toBe(4);
    expect(warnings).toEqual([]);
  });

  it('types parameters, bodies and responses with rows and full overloads', () => {
    expect(code).toContain('    /** Lists *\\/ widgets · GET /widget/v1/widgets · VIEW_WIDGET */');
    expect(code).toContain(
      '    getWidgets(params: { query: { wh_id: string | Date; status?: "A" | "X" | null; qty?: number | null } }, opts?: mk.ApiRowsOptions): Promise<Array<Def_widget_v1_Widget>>;',
    );
    expect(code).toContain(
      '    getWidgets(params: { query: { wh_id: string | Date; status?: "A" | "X" | null; qty?: number | null } }, opts: mk.ApiFullOptions): Promise<mk.ApiFullResult<{ data: Array<Def_widget_v1_Widget> }>>;',
    );
    expect(code).toContain('postWidgetMove(params: { body: { /** Warehouse */ wh_id: string; "odd-name"?: boolean } }, opts?: mk.ApiRowsOptions): Promise<{ moved?: number }>;');
    expect(code).toContain('deleteWidgetsByWidgetId(params: { path: { widget_id: string | number } }, opts?: mk.ApiRowsOptions): Promise<unknown>;');
    expect(code).toContain('getGizmos(params?: {}, opts?: mk.ApiRowsOptions): Promise<unknown>;');
  });

  it('emits only filtered operations and a never-like interface when empty', () => {
    const empty = emitApi({ ...snapshot, operations: [] }, { version: '0.5.0' });
    expect(empty.code).toContain('export interface MocaApi {}');
    expect(empty.code).toContain('export const API = {} as const satisfies mk.ApiSpecTable;');
    expect(empty.warnings).toEqual(['No API operations matched the api filters; moca.api.ts has no operations']);
  });

  it('uses importFrom and is deterministic', () => {
    expect(emitApi(snapshot, { version: '0.5.0', importFrom: '../../src/index.js' }).code).toContain("import type * as mk from '../../src/index.js';");
    expect(emitApi(snapshot, { version: '0.5.0' }).code).toBe(code);
  });
});
