import { readFileSync } from 'node:fs';
import { describe, expect, it } from 'vitest';
import { emit } from './emit.js';
import type { Snapshot } from './snapshot.js';

const snapshot = JSON.parse(
  readFileSync(new URL('../../test/fixtures/snapshot.json', import.meta.url), 'utf8'),
) as Snapshot;

describe('emit', () => {
  const { code, warnings } = emit(snapshot, { version: '0.1.0' });

  it('writes a header without credentials and imports mocakit as a namespace', () => {
    expect(code).toMatch(/^\/\/ AUTO-GENERATED by mocakit 0\.1\.0 from https:\/\/moca\.test\/service — 5 commands\./);
    expect(code).toContain(`import * as mk from "mocakit";`);
  });

  it('emits arg interfaces with required, optional, dtype mapping and quoted names', () => {
    expect(code).toContain('export interface ListOrdersArgs {');
    expect(code).toContain('  wh_id: string;');
    expect(code).toContain('  ordqty?: number | null;');
    expect(code).toContain('  adddte?: string | Date | null;');
    expect(code).toContain('  cancel_flg?: boolean | null;');
    expect(code).toContain('  "odd-name"?: string | null;');
    expect(code).toContain('  /** Warehouse (S) */');
  });

  it('emits the spec table', () => {
    expect(code).toContain(
      `  listOrders: ["list orders", [["ordnum", "S", 0], ["wh_id", "S", 1], ["ordqty", "I", 0], ["adddte", "D", 0], ["cancel_flg", "O", 0], ["odd-name", "S", 0]]],`,
    );
  });

  it('types commands through shared callable interfaces on a MocaClient subclass', () => {
    expect(code).toContain('export interface Moca extends mk.MocaClient {');
    expect(code).toContain(
      '  /** `list orders` · level: wmd · Lists orders */\n  listOrders: mk.Command<ListOrdersArgs, "list orders">;',
    );
    expect(code).toContain(`  listActiveCommands: mk.OptionalArgsCommand<mk.NoArgs, "list active commands">;`);
    expect(code).toContain(`  createInventory: mk.OptionalArgsCommand<CreateInventoryArgs, "create inventory">;`);
    expect(code).toContain('export class Moca extends mk.MocaClient {}\nmk.defineCommands(Moca.prototype, S);');
    expect(code).toContain('export function createMoca(config: mk.MocaConfig, deps?: mk.MocaClientDeps): Moca {');
    expect(code).not.toMatch(/<T = /);
  });

  it('handles reserved names, collisions and comment terminators', () => {
    expect(code).toContain('  cmdExec: mk.OptionalArgsCommand<mk.NoArgs, "exec">;');
    expect(code).toContain('  listOrders_2: mk.OptionalArgsCommand<mk.NoArgs, "list-orders">;');
    expect(code).toContain('Lists *\\/ active commands');
    expect(warnings).toEqual(['Commands "list orders", "list-orders" map to the same method name; generated listOrders, listOrders_2']);
  });

  it('exports the command-name union and is deterministic', () => {
    expect(code).toContain('export type MocaCommandName =\n  | "create inventory"\n');
    expect(emit(snapshot, { version: '0.1.0' }).code).toBe(code);
  });

  it('emits `never` for an empty command list', () => {
    expect(emit({ ...snapshot, commands: [] }, { version: '0.1.0' }).code).toContain('export type MocaCommandName = never;');
  });

  it('produces the same code for unsorted input', () => {
    const shuffled = { ...snapshot, commands: [...snapshot.commands].reverse() };
    const result = emit(shuffled, { version: '0.1.0' });
    expect(result.code).toBe(code);
    expect(result.warnings).toEqual(warnings);
  });

  it('emits a repeated command once, keeping the lowest-sorting name, whatever the input order', () => {
    const exec = snapshot.commands.find((c) => c.name === 'exec')!;
    const variants: Snapshot['commands'] = [
      { ...exec, name: 'exec', args: [{ name: 'a', dtype: 'S', required: false }] },
      { ...exec, name: 'EXEC', args: [] },
      { ...exec, name: ' exec ', args: [] },
    ];
    const forward = emit({ ...snapshot, commands: [...snapshot.commands.filter((c) => c !== exec), ...variants] }, { version: '0.1.0' });
    const backward = emit(
      { ...snapshot, commands: [...variants].reverse().concat(snapshot.commands.filter((c) => c !== exec)) },
      { version: '0.1.0' },
    );
    expect(backward.code).toBe(forward.code);
    expect(backward.warnings).toEqual(forward.warnings);
    // " exec " < "EXEC" < "exec" by code unit.
    expect(forward.code).toContain('  cmdExec: [" exec ", []],');
    expect(forward.code).toMatch(/— 5 commands\./);
    expect(forward.warnings).toEqual([
      'Command "EXEC" duplicates " exec "; kept " exec "',
      'Command "exec" duplicates " exec "; kept " exec "',
      'Commands "list orders", "list-orders" map to the same method name; generated listOrders, listOrders_2',
    ]);
  });

  it('keeps the first of repeated argument names, case-insensitively, and warns', () => {
    const result = emit(
      {
        ...snapshot,
        commands: [
          {
            name: 'dup args',
            args: [
              { name: 'wh_id', dtype: 'S', required: true },
              { name: 'WH_ID', dtype: 'I', required: false },
              { name: 'wh_id', dtype: 'S', required: false },
            ],
          },
        ],
      },
      { version: '0.1.0' },
    );
    expect(result.code).toContain('  dupArgs: ["dup args", [["wh_id", "S", 1]]],');
    expect(result.code).not.toContain('WH_ID');
    expect(result.warnings).toEqual([
      'Command "dup args" lists argument "WH_ID" more than once; kept the first',
      'Command "dup args" lists argument "wh_id" more than once; kept the first',
    ]);
  });

  it('escapes JSDoc tags and backticks from server text', () => {
    const result = emit(
      {
        ...snapshot,
        commands: [
          {
            name: 'odd `cmd`',
            description: '@deprecated use {@link x} or mail a@b.c',
            args: [{ name: 'x', dtype: 'S', required: false, description: '@param evil' }],
          },
        ],
      },
      { version: '0.1.0' },
    );
    expect(result.code).toContain("  /** `odd 'cmd'` · \\@deprecated use {\\@link x} or mail a@b.c */");
    expect(result.code).toContain('  /** \\@param evil (S) */');
  });

  it('quotes an argument named __proto__', () => {
    const result = emit(
      { ...snapshot, commands: [{ name: 'proto', args: [{ name: '__proto__', dtype: 'S', required: false }] }] },
      { version: '0.1.0' },
    );
    expect(result.code).toContain('  "__proto__"?: string | null;');
  });
});
