import { redactUrl } from '../util/url.js';
import type { ApiOperation, ApiSchema, ApiSnapshot } from './api-snapshot.js';
import { doc, propertyName } from './emit.js';
import { globToRegExp } from './filter.js';
import { byCodeUnit } from './names.js';

export interface ApiFilter {
  /** Tag key globs (`widget`, `inv*`), case-insensitive. Default all. */
  include?: string[];
  exclude?: string[];
  /** Lowercase HTTP methods. Default all. */
  methods?: string[];
}

export function filterOperations(ops: ApiOperation[], filter: ApiFilter): ApiOperation[] {
  const include = (filter.include?.length ? filter.include : ['*']).map(globToRegExp);
  const exclude = (filter.exclude ?? []).map(globToRegExp);
  const methods = filter.methods?.length ? new Set(filter.methods.map((m) => m.toLowerCase())) : null;
  return ops.filter(
    (op) => include.some((re) => re.test(op.tagKey)) && !exclude.some((re) => re.test(op.tagKey)) && (methods === null || methods.has(op.method)),
  );
}

export function defTypeNames(names: string[]): Map<string, string> {
  const result = new Map<string, string>();
  const taken = new Set<string>();
  for (const name of names) {
    const base = `Def_${name.replace(/[^A-Za-z0-9_$]/g, '_')}`;
    let candidate = base;
    for (let n = 2; taken.has(candidate); n++) candidate = `${base}_${n}`;
    taken.add(candidate);
    result.set(name, candidate);
  }
  return result;
}

const str = (v: string): string => JSON.stringify(v);

export function tsApiType(schema: ApiSchema, defs: Map<string, string>, indent = ''): string {
  switch (schema.kind) {
    case 'string':
      return schema.enum?.length ? schema.enum.map(str).join(' | ') : 'string';
    case 'number':
      return 'number';
    case 'boolean':
      return 'boolean';
    case 'array':
      return `Array<${tsApiType(schema.items, defs, indent)}>`;
    case 'ref':
      return defs.get(schema.name) ?? 'unknown';
    case 'object': {
      const entries = Object.entries(schema.properties);
      if (entries.length === 0) return schema.additional !== undefined ? `Record<string, ${tsApiType(schema.additional, defs, indent)}>` : '{}';
      const fields = entries.map(([name, prop]) => {
        const optional = schema.required.includes(name) ? '' : '?';
        const comment = prop.description !== undefined ? `/** ${doc(prop.description)} */ ` : '';
        return `${comment}${propertyName(name)}${optional}: ${tsApiType(prop, defs, indent)}`;
      });
      return `{ ${fields.join('; ')} }`;
    }
    default:
      return 'unknown';
  }
}

function queryValueType(schema: ApiSchema, defs: Map<string, string>): string {
  if (schema.kind === 'string' && !schema.enum?.length) return 'string | Date';
  if (schema.kind === 'array') return `Array<${queryValueType(schema.items, defs)}>`;
  return tsApiType(schema, defs);
}

function paramsType(op: ApiOperation, defs: Map<string, string>): { type: string; optional: boolean } {
  const parts: string[] = [];
  let anyRequired = false;
  const group = (where: 'path' | 'query' | 'formData', key: string, pathStyle: boolean) => {
    const ps = op.parameters.filter((p) => p.in === where);
    if (ps.length === 0) return;
    const required = ps.some((p) => p.required);
    anyRequired ||= required;
    const fields = ps.map((p) =>
      pathStyle
        ? `${propertyName(p.name)}: string | number`
        : `${propertyName(p.name)}${p.required ? '' : '?'}: ${queryValueType(p.schema, defs)}${p.required ? '' : ' | null'}`,
    );
    parts.push(`${key}${required ? '' : '?'}: { ${fields.join('; ')} }`);
  };
  group('path', 'path', true);
  group('query', 'query', false);
  group('formData', 'form', false);
  if (op.body !== undefined) {
    anyRequired ||= op.body.required;
    parts.push(`body${op.body.required ? '' : '?'}: ${tsApiType(op.body.schema, defs)}`);
  }
  return { type: `{ ${parts.join('; ')} }`.replace('{  }', '{}'), optional: !anyRequired };
}

function returnTypes(op: ApiOperation, defs: Map<string, string>): { rows: string; full: string } {
  if (op.response === undefined) return { rows: 'unknown', full: 'unknown' };
  const t = tsApiType(op.response.schema, defs);
  return op.response.envelope === 'data' ? { rows: `Array<${t}>`, full: `{ data: Array<${t}> }` } : { rows: t, full: t };
}

export function emitApi(snapshot: ApiSnapshot, options: { version: string; importFrom?: string }): { code: string; warnings: string[]; count: number } {
  const ops = snapshot.operations;
  const warnings = ops.length === 0 ? ['No API operations matched the api filters; moca.api.ts has no operations'] : [];
  const defNames = Object.keys(snapshot.definitions).sort(byCodeUnit);
  const defs = defTypeNames(defNames);
  const lines = [
    `// AUTO-GENERATED by mocakit ${options.version} from ${redactUrl(snapshot.server)} — ${ops.length} API operations.`,
    '// Do not edit by hand; regenerate with `mocakit generate`.',
    '/* eslint-disable */',
    `import type * as mk from '${options.importFrom ?? 'mocakit'}';`,
    '',
  ];
  for (const name of defNames) {
    const schema = snapshot.definitions[name]!;
    const typeName = defs.get(name)!;
    if (schema.kind === 'object' && Object.keys(schema.properties).length > 0) {
      lines.push(`export interface ${typeName} {`);
      for (const [prop, s] of Object.entries(schema.properties)) {
        if (s.description !== undefined) lines.push(`  /** ${doc(s.description)} */`);
        lines.push(`  ${propertyName(prop)}${schema.required.includes(prop) ? '' : '?'}: ${tsApiType(s, defs)};`);
      }
      lines.push('}', '');
    } else {
      lines.push(`export type ${typeName} = ${tsApiType(schema, defs)};`, '');
    }
  }
  const byTag = new Map<string, ApiOperation[]>();
  for (const op of ops) byTag.set(op.tagKey, [...(byTag.get(op.tagKey) ?? []), op]);
  const tags = [...byTag.keys()].sort(byCodeUnit);

  if (tags.length === 0) lines.push('export interface MocaApi {}', '');
  else {
    lines.push('export interface MocaApi {');
    for (const tag of tags) {
      lines.push(`  ${propertyName(tag)}: {`);
      for (const op of byTag.get(tag)!) {
        const meta = [op.description, `${op.method.toUpperCase()} ${op.path}`, op.permissions.join(', ') || undefined].filter((x) => x !== undefined).join(' · ');
        const p = paramsType(op, defs);
        const r = returnTypes(op, defs);
        const param = `params${p.optional ? '?' : ''}: ${p.type}`;
        lines.push(
          `    /** ${doc(meta)} */`,
          `    ${propertyName(op.name)}(${param}, opts?: mk.ApiRowsOptions): Promise<${r.rows}>;`,
          `    ${propertyName(op.name)}(params: ${p.type}${p.optional ? ' | undefined' : ''}, opts: mk.ApiFullOptions): Promise<mk.ApiFullResult<${r.full}>>;`,
        );
      }
      lines.push('  };');
    }
    lines.push('}', '');
  }

  if (tags.length === 0) lines.push('export const API = {} as const satisfies mk.ApiSpecTable;', '');
  else {
    lines.push('export const API = {');
    for (const tag of tags) {
      lines.push(`  ${propertyName(tag)}: {`);
      for (const op of byTag.get(tag)!) lines.push(`    ${propertyName(op.name)}: [${str(op.method)}, ${str(op.fullPath)}, ${str(op.response?.envelope ?? 'body')}],`);
      lines.push('  },');
    }
    lines.push('} as const satisfies mk.ApiSpecTable;', '');
  }
  return { code: lines.join('\n'), warnings, count: ops.length };
}
