import { redactUrl } from '../util/url.js';
import { describeType } from './emit-schema.js';
import { checkDocsTargets, docHref, DOC_MARKER, encodeDocName, writeDocs } from './docs-writer.js';
import type { SchemaSnapshot, SchemaTable } from './schema-snapshot.js';

export { DOC_MARKER } from './docs-writer.js';

const SAFE = /^[a-z0-9_$#]$/;

export function docFileName(table: string): { file: string; encoded: boolean } {
  return encodeDocName(table, SAFE);
}

const oneLine = (text: string): string => text.replace(/\s+/g, ' ').trim();
const cell = (text: string | undefined): string => (text === undefined ? '' : oneLine(text).replace(/\\/g, '\\\\').replace(/\|/g, '\\|'));

function readme(marker: string): string {
  return [
    marker,
    '# Database schema (for coding agents)',
    '',
    'This folder describes the tables and views of the MOCA database, generated by `mocakit generate`.',
    '',
    '- Search `INDEX.md` for candidate tables by name or description, then open `tables/<table>.md` for its columns.',
    '- Names are lowercase. Dates arrive as `YYYYMMDDHH24MISS` strings.',
    "- Query a single table with `moca.from('table').select(...).where({...}).rows()`; use `moca.exec('[select ...]')`",
    '  for joins and anything more complex. Types for every table are in `moca.schema.ts`.',
    '',
  ].join('\n');
}

function tableFile(marker: string, table: SchemaTable): string {
  const key = table.primaryKey?.length ? ` · primary key: ${table.primaryKey.join(', ')}` : '';
  const lines = [marker, `# ${table.name}`, '', `${table.kind}${key}`, ''];
  if (table.comment !== undefined) lines.push(oneLine(table.comment), '');
  lines.push('| column | type | null | key | comment |', '|---|---|---|---|---|');
  for (const column of table.columns) {
    const pk = table.primaryKey?.includes(column.name) ? 'PK' : '';
    lines.push(`| ${cell(column.name)} | ${cell(describeType(column))} | ${column.nullable ? 'yes' : 'no'} | ${pk} | ${cell(column.comment)} |`);
  }
  lines.push('');
  return lines.join('\n');
}

/** Pure: the docs folder as a map of relative path → content. */
export function emitSchemaDocs(snapshot: SchemaSnapshot, options: { version: string }): { files: Map<string, string>; warnings: string[] } {
  const marker = `${DOC_MARKER} ${options.version} from ${redactUrl(snapshot.server)}. Do not edit; regenerate with \`mocakit generate\`. -->`;
  const warnings: string[] = [];
  const files = new Map<string, string>([['README.md', readme(marker)]]);
  const index = [marker, '# Tables and views', ''];
  const tableFiles: Array<[string, string]> = [];
  for (const table of snapshot.tables) {
    const { file, encoded } = docFileName(table.name);
    if (encoded) warnings.push(`Table "${table.name}" has characters that are not safe in file names; its doc is tables/${file}`);
    const cols = `${table.columns.length} ${table.columns.length === 1 ? 'col' : 'cols'}`;
    const comment = table.comment === undefined ? '' : ` · ${oneLine(table.comment)}`;
    index.push(`- [\`${table.name}\`](tables/${docHref(file)}) · ${table.kind} · ${cols}${comment}`);
    tableFiles.push([`tables/${file}`, tableFile(marker, table)]);
  }
  index.push('');
  files.set('INDEX.md', index.join('\n'));
  for (const [path, content] of tableFiles) files.set(path, content);
  return { files, warnings };
}

/** Throws if any target already exists and was not generated by mocakit (never overwrite hand-written files). */
export function checkSchemaDocsTargets(dir: string, files: ReadonlyMap<string, string>): Promise<void> {
  return checkDocsTargets(dir, files, 'schema.docs');
}

/** Writes changed files and deletes stale generated `tables/*.md` and `codes/*.md` files. */
export function writeSchemaDocs(dir: string, files: ReadonlyMap<string, string>): ReturnType<typeof writeDocs> {
  return writeDocs(dir, files, { setting: 'schema.docs', managedDirs: ['tables', 'codes'] });
}
