import { redactUrl } from '../util/url.js';
import { describeType } from './emit-schema.js';
import { checkDocsTargets, docHref, DOC_MARKER, encodeDocName, PRIVATE_NOTICE, writeDocs } from './docs-writer.js';
import type { ColumnCodes, SchemaSnapshot, SchemaTable, TableUsage } from './schema-snapshot.js';

export { DOC_MARKER } from './docs-writer.js';

const SAFE = /^[a-z0-9_$#]$/;

export function docFileName(table: string): { file: string; encoded: boolean } {
  return encodeDocName(table, SAFE);
}

const oneLine = (text: string): string => text.replace(/\s+/g, ' ').trim();
const cell = (text: string | undefined): string => (text === undefined ? '' : oneLine(text).replace(/\\/g, '\\\\').replace(/\|/g, '\\|'));

function readme(marker: string): string {
  return [
    marker,
    PRIVATE_NOTICE,
    '# Database schema (for coding agents)',
    '',
    'This folder describes the tables and views of the MOCA database, generated by `mocakit generate`.',
    '',
    '- Search `INDEX.md` for candidate tables by name or description, then open `tables/<table>.md` for its columns.',
    '- Coded columns link to `codes/<column>.md` with each value\'s meaning.',
    '- Names are lowercase. Dates arrive as `YYYYMMDDHH24MISS` strings.',
    "- Query a single table with `moca.from('table').select(...).where({...}).rows()`; use `moca.exec('[select ...]')`",
    '  for joins and anything more complex. Types for every table are in `moca.schema.ts`.',
    '',
  ].join('\n');
}

/** Link to a command's doc, or undefined when that command has no doc (shown as a plain name). */
type CommandHref = (command: string) => string | undefined;

function tableFile(marker: string, table: SchemaTable, coded: ReadonlyMap<string, ColumnCodes>, entry: TableUsage | undefined, commandHref: CommandHref | undefined): string {
  const key = table.primaryKey?.length ? ` · primary key: ${table.primaryKey.join(', ')}` : '';
  const lines = [marker, `# ${table.name}`, '', `${table.kind}${key}`, ''];
  if (table.comment !== undefined) lines.push(oneLine(table.comment), '');
  lines.push('| column | type | null | key | comment |', '|---|---|---|---|---|');
  for (const column of table.columns) {
    const pk = table.primaryKey?.includes(column.name) ? 'PK' : '';
    const codesLink = coded.has(column.name) ? `[codes](../codes/${docHref(docFileName(column.name).file)})` : '';
    const comment = [cell(column.comment), codesLink].filter((part) => part !== '').join(' · ');
    lines.push(`| ${cell(column.name)} | ${cell(describeType(column))} | ${column.nullable ? 'yes' : 'no'} | ${pk} | ${comment} |`);
  }
  lines.push('');
  if (entry && (entry.readBy.length > 0 || entry.writtenBy.length > 0)) {
    const link = (name: string) => {
      const href = commandHref?.(name);
      return href === undefined ? `\`${name}\`` : `[\`${name}\`](${docHref(href)})`;
    };
    const list = (names: string[]) => (names.length > 50 ? `${names.slice(0, 50).map(link).join(', ')}, and ${names.length - 50} more` : names.map(link).join(', '));
    lines.push('## Used by (approximate, from command source)', '');
    if (entry.readBy.length > 0) lines.push(`- Read by: ${list(entry.readBy)}`);
    if (entry.writtenBy.length > 0) lines.push(`- Written by: ${list(entry.writtenBy)}`);
    lines.push('');
  }
  return lines.join('\n');
}

/** Pure: the docs folder as a map of relative path → content. */
export function emitSchemaDocs(snapshot: SchemaSnapshot, options: { version: string; commandHref?: CommandHref }): { files: Map<string, string>; warnings: string[] } {
  const marker = `${DOC_MARKER} ${options.version} from ${redactUrl(snapshot.server)}. Do not edit; regenerate with \`mocakit generate\`. -->`;
  const warnings: string[] = [];
  const coded = new Map((snapshot.codes?.columns ?? []).map((c) => [c.column, c] as const));
  const usage = new Map((snapshot.usage ?? []).map((u) => [u.table, u] as const));
  const files = new Map<string, string>([['README.md', readme(marker)]]);
  const index = [marker, PRIVATE_NOTICE, '# Tables and views', ''];
  const tableFiles: Array<[string, string]> = [];
  for (const table of snapshot.tables) {
    const { file, encoded } = docFileName(table.name);
    if (encoded) warnings.push(`Table "${table.name}" has characters that are not safe in file names; its doc is tables/${file}`);
    const cols = `${table.columns.length} ${table.columns.length === 1 ? 'col' : 'cols'}`;
    const comment = table.comment === undefined ? '' : ` · ${oneLine(table.comment)}`;
    index.push(`- [\`${table.name}\`](tables/${docHref(file)}) · ${table.kind} · ${cols}${comment}`);
    tableFiles.push([`tables/${file}`, tableFile(marker, table, coded, usage.get(table.name), options.commandHref)]);
  }
  index.push('');
  files.set('INDEX.md', index.join('\n'));
  for (const [path, content] of tableFiles) files.set(path, content);
  for (const col of [...coded.values()].sort((a, b) => (a.column < b.column ? -1 : a.column > b.column ? 1 : 0))) {
    const codeLines = [marker, `# ${col.column} codes (${snapshot.codes!.locale})`, '', '| value | short | description |', '|---|---|---|'];
    for (const v of col.values) codeLines.push(`| ${cell(v.value)} | ${cell(v.short)} | ${cell(v.long)} |`);
    files.set(`codes/${docFileName(col.column).file}`, `${codeLines.join('\n')}\n`);
  }
  return { files, warnings };
}

/** Throws if any target already exists and was not generated by mocakit (never overwrite hand-written files). */
export function checkSchemaDocsTargets(dir: string, files: ReadonlyMap<string, string>): Promise<void> {
  return checkDocsTargets(dir, files, 'schema.docs');
}

/** Writes changed files and deletes stale generated `tables/*.md` and `codes/*.md` files. */
export function writeSchemaDocs(dir: string, files: ReadonlyMap<string, string>): ReturnType<typeof writeDocs> {
  return writeDocs(dir, files, { setting: 'schema.docs', managedDirs: ['tables', 'codes'] });
}
