import { readFileSync } from 'node:fs';
import { describe, expect, it } from 'vitest';
import { emit } from './emit.js';
import type { Snapshot } from './snapshot.js';

const snapshot = JSON.parse(
  readFileSync(new URL('../../test/fixtures/snapshot.json', import.meta.url), 'utf8'),
) as Snapshot;

const POINTER_WARNING =
  'Command "consume widget pointer" requires stack argument "widget_ptr" (POINTER); skipped (run it with exec())';
const ODD_NAME_WARNING =
  'Command "list orders" argument "odd-name" is not a valid MOCA argument name; dropped the argument';

describe('emit', () => {
  const { code, warnings } = emit(snapshot, { version: '0.1.0' });

  it('writes a header without credentials and imports mocakit as a namespace', () => {
    expect(code).toMatch(/^\/\/ AUTO-GENERATED by mocakit 0\.1\.0 from https:\/\/moca\.test\/service — 8 commands\./);
    expect(code).toContain(`import * as mk from "mocakit";`);
  });

  it('emits arg interfaces with required, optional, dtype mapping and quoted names', () => {
    expect(code).toContain('export interface ListOrdersArgs {');
    expect(code).toContain('  wh_id: string;');
    expect(code).toContain('  ordqty?: number | null;');
    expect(code).toContain('  adddte?: string | Date | null;');
    expect(code).toContain('  cancel_flg?: boolean | null;');
    expect(code).not.toContain('odd-name');
    expect(code).toContain('  /** Warehouse (S) */');
  });

  it('emits the spec table', () => {
    expect(code).toContain(
      `  listOrders: ["list orders", [["ordnum", "S", 0], ["wh_id", "S", 1], ["ordqty", "I", 0], ["adddte", "D", 0], ["cancel_flg", "O", 0]]],`,
    );
  });

  it('types commands through shared callable interfaces on a MocaClient subclass', () => {
    expect(code).toContain('export interface Moca extends mk.MocaClient {');
    expect(code).toContain(
      '  /** `list orders` · level: wmd · Lists orders */\n  listOrders: mk.Command<ListOrdersArgs, "list orders">;',
    );
    expect(code).toContain(`  listActiveCommands: mk.OptionalArgsCommand<mk.NoArgs, "list active commands">;`);
    expect(code).toContain(`  createInventory: mk.OptionalArgsCommand<CreateInventoryArgs, "create inventory">;`);
    expect(code).toContain('export class Moca extends mk.MocaClient {}\nmk.defineCommands(Moca.prototype, S);');
    expect(code).toContain('export function createMoca(config: mk.MocaConfig, deps?: mk.MocaClientDeps): Moca {');
    expect(code).not.toMatch(/<T = /);
  });

  it('handles reserved names, collisions and comment terminators', () => {
    expect(code).toContain('  cmdExec: mk.OptionalArgsCommand<mk.NoArgs, "exec">;');
    expect(code).toContain('  listOrders_2: mk.OptionalArgsCommand<mk.NoArgs, "list-orders">;');
    expect(code).toContain('Lists *\\/ active commands');
    expect(warnings).toEqual([
      POINTER_WARNING,
      ODD_NAME_WARNING,
      'Commands "list orders", "list-orders" map to the same method name; generated listOrders, listOrders_2',
    ]);
  });

  it('exports the command-name union and is deterministic', () => {
    expect(code).toContain('export type MocaCommandName =\n  | "assign dock door"\n  | "create inventory"\n');
    expect(emit(snapshot, { version: '0.1.0' }).code).toBe(code);
  });

  it('emits `never` for an empty command list', () => {
    expect(emit({ ...snapshot, commands: [] }, { version: '0.1.0' }).code).toContain('export type MocaCommandName = never;');
  });

  it('produces the same code for unsorted input', () => {
    const shuffled = { ...snapshot, commands: [...snapshot.commands].reverse() };
    const result = emit(shuffled, { version: '0.1.0' });
    expect(result.code).toBe(code);
    expect(result.warnings).toEqual(warnings);
  });

  it('emits a repeated command once, keeping the lowest-sorting name, whatever the input order', () => {
    const exec = snapshot.commands.find((c) => c.name === 'exec')!;
    const variants: Snapshot['commands'] = [
      { ...exec, name: 'exec', args: [{ name: 'a', dtype: 'S', required: false }] },
      { ...exec, name: 'EXEC', args: [] },
      { ...exec, name: ' exec ', args: [] },
    ];
    const forward = emit({ ...snapshot, commands: [...snapshot.commands.filter((c) => c !== exec), ...variants] }, { version: '0.1.0' });
    const backward = emit(
      { ...snapshot, commands: [...variants].reverse().concat(snapshot.commands.filter((c) => c !== exec)) },
      { version: '0.1.0' },
    );
    expect(backward.code).toBe(forward.code);
    expect(backward.warnings).toEqual(forward.warnings);
    // " exec " < "EXEC" < "exec" by code unit.
    expect(forward.code).toContain('  cmdExec: [" exec ", []],');
    expect(forward.code).toMatch(/— 8 commands\./);
    expect(forward.warnings).toEqual([
      'Command "EXEC" duplicates " exec "; kept " exec "',
      POINTER_WARNING,
      'Command "exec" duplicates " exec "; kept " exec "',
      ODD_NAME_WARNING,
      'Commands "list orders", "list-orders" map to the same method name; generated listOrders, listOrders_2',
    ]);
  });

  it('keeps the first of repeated argument names, case-insensitively, and warns', () => {
    const result = emit(
      {
        ...snapshot,
        commands: [
          {
            name: 'dup args',
            args: [
              { name: 'wh_id', dtype: 'S', required: true },
              { name: 'WH_ID', dtype: 'I', required: false },
              { name: 'wh_id', dtype: 'S', required: false },
            ],
          },
        ],
      },
      { version: '0.1.0' },
    );
    expect(result.code).toContain('  dupArgs: ["dup args", [["wh_id", "S", 1]]],');
    expect(result.code).not.toContain('WH_ID');
    expect(result.warnings).toEqual([
      'Command "dup args" lists argument "WH_ID" more than once; kept the first',
      'Command "dup args" lists argument "wh_id" more than once; kept the first',
    ]);
  });

  it('escapes JSDoc tags and backticks from server text', () => {
    const result = emit(
      {
        ...snapshot,
        commands: [
          {
            name: 'odd `cmd`',
            description: '@deprecated use {@link x} or mail a@b.c',
            args: [{ name: 'x', dtype: 'S', required: false, description: '@param evil' }],
          },
        ],
      },
      { version: '0.1.0' },
    );
    expect(result.code).toContain("  /** `odd 'cmd'` · \\@deprecated use {\\@link x} or mail a@b.c */");
    expect(result.code).toContain('  /** \\@param evil (S) */');
  });

  it('quotes an argument named __proto__', () => {
    const result = emit(
      { ...snapshot, commands: [{ name: 'proto', args: [{ name: '__proto__', dtype: 'S', required: false }] }] },
      { version: '0.1.0' },
    );
    expect(result.code).toContain('  "__proto__"?: string | null;');
  });

  it('returns the number of commands it emitted', () => {
    expect(emit(snapshot, { version: '0.1.0' }).count).toBe(8);
    const withDuplicate = { ...snapshot, commands: [...snapshot.commands, { name: 'EXEC', args: [] }] };
    expect(emit(withDuplicate, { version: '0.1.0' }).count).toBe(8);
  });

  it('skips a command whose required argument name is not a valid MOCA argument name, and warns', () => {
    const result = emit(
      {
        ...snapshot,
        commands: [
          { name: 'bad required', args: [{ name: 'wh-id', dtype: 'S', required: true }] },
          { name: 'good', args: [{ name: 'wh_id', dtype: 'S', required: true }] },
        ],
      },
      { version: '0.1.0' },
    );
    expect(result.code).not.toContain('bad required');
    expect(result.code).not.toContain('badRequired');
    expect(result.code).toContain('  good: ["good", [["wh_id", "S", 1]]],');
    expect(result.code).toMatch(/— 1 commands\./);
    expect(result.count).toBe(1);
    expect(result.warnings).toEqual([
      'Command "bad required" requires argument "wh-id", which is not a valid MOCA argument name; skipped the command',
    ]);
  });

  it('drops an optional argument whose name is not a valid MOCA argument name, including $-names', () => {
    const result = emit(
      { ...snapshot, commands: [{ name: 'c', args: [{ name: '$x', dtype: 'S', required: false }, { name: 'y', dtype: 'S', required: false }] }] },
      { version: '0.1.0' },
    );
    expect(result.code).toContain('  c: ["c", [["y", "S", 0]]],');
    expect(result.warnings).toEqual(['Command "c" argument "$x" is not a valid MOCA argument name; dropped the argument']);
  });
  describe('live-server argument rules', () => {
    const one = (args: Snapshot['commands'][number]['args'], name = 'cmd') =>
      emit({ ...snapshot, commands: [{ name, args }] }, { version: '0.1.0' });

    it('maps FLAG to boolean, UNKNOWN to any scalar and STRING to string', () => {
      expect(code).toContain('export interface AssignDockDoorArgs {');
      expect(code).toContain('  rush_flg?: boolean | null;');
      expect(code).toContain('  priority?: string | number | boolean | Date | null;');
      expect(code).toContain('  widget_id: string;');
    });

    it('strips a leading @ from argument names and dedupes the bare name silently', () => {
      expect(code).toContain('  door_id: string;');
      expect(code).not.toContain('@door_id');
      expect(code).toContain(
        '  assignDockDoor: ["assign dock door", [["door_id", "STRING", 1], ["rush_flg", "FLAG", 0], ["priority", "UNKNOWN", 0]]],',
      );
      expect(code).toContain('  assignDockDoor: mk.Command<AssignDockDoorArgs, "assign dock door">;');
      expect(warnings.some((w) => w.includes('door_id'))).toBe(false);
    });

    it('strips @+ as well, and keeps a required @name command callable', () => {
      const result = one([
        { name: '@wh_id', dtype: 'STRING', required: true },
        { name: '@+prtnum', dtype: 'STRING', required: false },
      ]);
      expect(result.code).toContain('  cmd: ["cmd", [["wh_id", "STRING", 1], ["prtnum", "STRING", 0]]],');
      expect(result.count).toBe(1);
      expect(result.warnings).toEqual([]);
    });

    it('still warns on a case-only duplicate once the @ is stripped', () => {
      const result = one([
        { name: '@wh_id', dtype: 'STRING', required: false },
        { name: '@WH_ID', dtype: 'STRING', required: false },
      ]);
      expect(result.code).toContain('  cmd: ["cmd", [["wh_id", "STRING", 0]]],');
      expect(result.warnings).toEqual(['Command "cmd" lists argument "@WH_ID" more than once; kept the first']);
    });

    it('still warns on names that are invalid after stripping @', () => {
      const dropped = one([
        { name: '@1abc', dtype: 'STRING', required: false },
        { name: 'my arg', dtype: 'STRING', required: false },
      ]);
      expect(dropped.warnings).toEqual([
        'Command "cmd" argument "@1abc" is not a valid MOCA argument name; dropped the argument',
        'Command "cmd" argument "my arg" is not a valid MOCA argument name; dropped the argument',
      ]);
      const skipped = one([{ name: '@9x', dtype: 'STRING', required: true }]);
      expect(skipped.count).toBe(0);
      expect(skipped.warnings).toEqual([
        'Command "cmd" requires argument "@9x", which is not a valid MOCA argument name; skipped the command',
      ]);
    });

    it('marks wildcard commands as pass-through and drops the wildcard silently', () => {
      expect(code).toContain(
        [
          '  /**',
          '   * `process widgets` · level: wmd · Processes widgets',
          '   * Accepts additional arguments (wildcard: \\@*): pass them via opts.extraArgs.',
          '   */',
          '  processWidgets: mk.Command<ProcessWidgetsArgs, "process widgets">;',
        ].join('\n'),
      );
      expect(code).toContain('  processWidgets: ["process widgets", [["widget_id", "STRING", 1]]],');
      expect(code).not.toContain('"@*"');
      expect(code).not.toContain('widget.*');
      expect(warnings.some((w) => w.includes('*'))).toBe(false);
    });

    it('recognises every wildcard form, required or not', () => {
      for (const name of ['@*', '*', '@+widget.*', 'foo.*', '@foo.*', '@+*']) {
        const result = one([{ name, dtype: 'STRING', required: name === '*' }]);
        expect(result.warnings, name).toEqual([]);
        expect(result.count, name).toBe(1);
        expect(result.code, name).toContain('  cmd: ["cmd", []],');
        const shown = name.replace('@', '\\@');
        expect(result.code, name).toContain(`   * Accepts additional arguments (wildcard: ${shown}): pass them via opts.extraArgs.`);
        expect(result.code, name).toContain('  cmd: mk.OptionalArgsCommand<mk.NoArgs, "cmd">;');
      }
    });

    it('names the first wildcard seen in the pass-through note', () => {
      const result = one([
        { name: 'foo.*', dtype: 'STRING', required: false },
        { name: '@*', dtype: 'UNKNOWN', required: false },
      ]);
      expect(result.code).toContain('   * Accepts additional arguments (wildcard: foo.*): pass them via opts.extraArgs.');
      expect(result.code).not.toContain('wildcard: \\@*');
    });

    it('makes a deduped argument required if either entry is required, keeping the first name and dtype', () => {
      const optionalFirst = one([
        { name: 'wh_id', dtype: 'STRING', required: false },
        { name: '@wh_id', dtype: 'STRING', required: true },
      ]);
      expect(optionalFirst.code).toContain('  cmd: ["cmd", [["wh_id", "STRING", 1]]],');
      expect(optionalFirst.code).toContain('  cmd: mk.Command<CmdArgs, "cmd">;');
      expect(optionalFirst.warnings).toEqual([]);

      const renamed = one([
        { name: '@Wh_Id', dtype: 'INTEGER', required: false },
        { name: 'wh_id', dtype: 'STRING', required: true },
      ]);
      expect(renamed.code).toContain('  cmd: ["cmd", [["Wh_Id", "INTEGER", 1]]],');
      expect(renamed.code).toContain('  Wh_Id: number;');
    });

    it('prefers the non-stack entry when a deduped name is stack-typed in only one entry', () => {
      for (const args of [
        [
          { name: '@res', dtype: 'RESULTS', required: true },
          { name: 'res', dtype: 'STRING', required: false },
        ],
        [
          { name: 'res', dtype: 'STRING', required: false },
          { name: '@res', dtype: 'RESULTS', required: true },
        ],
      ]) {
        const result = one(args);
        expect(result.count).toBe(1);
        expect(result.warnings).toEqual([]);
        expect(result.code).toContain('  cmd: ["cmd", [["res", "STRING", 1]]],');
        expect(result.code).not.toContain('Stack-only');
      }
    });

    it('keeps the first entry when both deduped entries are stack-typed, and skips if either is required', () => {
      const result = one([
        { name: '@r', dtype: 'RESULTS', required: false },
        { name: 'r', dtype: 'POINTER', required: true },
      ]);
      expect(result.count).toBe(0);
      expect(result.warnings).toEqual(['Command "cmd" requires stack argument "r" (RESULTS); skipped (run it with exec())']);
    });

    it('leaves optional stack arguments out of the interface and spec, noting them in JSDoc', () => {
      expect(code).toContain('export interface SummarizeWidgetsArgs {\n  /** (STRING) */\n  widget_id?: string | null;\n}');
      expect(code).toContain('  summarizeWidgets: ["summarize widgets", [["widget_id", "STRING", 0]]],');
      expect(code).toContain(
        [
          '  /**',
          '   * `summarize widgets` · level: wmd',
          '   * Stack-only arguments not settable here: result_set (RESULTS), blob (BINARY)',
          '   */',
          '  summarizeWidgets: mk.OptionalArgsCommand<SummarizeWidgetsArgs, "summarize widgets">;',
        ].join('\n'),
      );
      expect(code).not.toContain('result_set?');
      expect(warnings.some((w) => w.includes('summarize widgets'))).toBe(false);
    });

    it('skips a command whose required argument is a stack type, and warns', () => {
      expect(code).not.toContain('consume widget pointer');
      expect(code).not.toContain('consumeWidgetPointer');
      expect(warnings).toContain(POINTER_WARNING);
      for (const dtype of ['RESULTS', 'OBJECT', 'BINARY', 'pointer']) {
        const result = one([{ name: '@pickresults', dtype, required: true }], 'pick things');
        expect(result.count).toBe(0);
        expect(result.warnings).toEqual([
          `Command "pick things" requires stack argument "pickresults" (${dtype}); skipped (run it with exec())`,
        ]);
      }
    });

    it('emits both JSDoc lines when a command has a wildcard and a stack argument', () => {
      const result = one([
        { name: '@*', dtype: 'UNKNOWN', required: false },
        { name: 'obj', dtype: 'OBJECT', required: false },
      ]);
      expect(result.code).toContain(
        [
          '  /**',
          '   * `cmd`',
          '   * Accepts additional arguments (wildcard: \\@*): pass them via opts.extraArgs.',
          '   * Stack-only arguments not settable here: obj (OBJECT)',
          '   */',
          '  cmd: mk.OptionalArgsCommand<mk.NoArgs, "cmd">;',
        ].join('\n'),
      );
    });
  });
});
